services:
  - type: web
    name: managrr
    runtime: go
    plan: free
    buildCommand: chmod +x backend/scripts/build.sh && backend/scripts/build.sh && cd backend && go build -o app
    startCommand: cd backend && ./app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPAID
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: APP_URL
        sync: false
      - key: FROM_NAME
        value: Managrr
      - key: ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /health
    autoDeploy: false