import { theme } from "../theme"

export const projectDetailStyles = {
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "2rem 1rem",
    minHeight: "calc(100vh - 100px)",
  },
  loading: {
    textAlign: "center",
    padding: "3rem 1rem",
    fontSize: theme.typography.bodyLarge.fontSize,
    color: theme.colors.textLight,
  },
  error: {
    textAlign: "center",
    padding: "3rem 1rem",
    fontSize: theme.typography.bodyLarge.fontSize,
  },
  errorButton: {
    marginTop: theme.spacing.component,
    padding: "0.875rem 1.5rem",
    backgroundColor: theme.colors.black,
    color: theme.colors.white,
    border: "none",
    borderRadius: theme.borderRadius.md,
    cursor: "pointer",
    fontSize: theme.typography.body.fontSize,
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: theme.spacing.component,
    gap: "1rem",
    flexWrap: "wrap",
  },
  backButton: {
    padding: "0.875rem 1.5rem",
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.borderRadius.md,
    cursor: "pointer",
    fontSize: theme.typography.body.fontSize,
    backgroundColor: theme.colors.white,
    color: theme.colors.text,
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  editButton: {
    padding: "0.875rem 1.5rem",
    backgroundColor: theme.colors.text,
    color: theme.colors.white,
    border: "none",
    borderRadius: theme.borderRadius.md,
    cursor: "pointer",
    fontSize: "0.9375rem",
    fontWeight: "600",
    transition: "all 0.2s ease",
    boxShadow: theme.shadows.sm,
    letterSpacing: "0.01em",
  },
  infoCard: {
    background: theme.colors.white,
    padding: "2rem",
    borderRadius: theme.borderRadius.lg,
    boxShadow: theme.shadows.md,
    marginBottom: "2rem",
    border: `1px solid ${theme.colors.borderLight}`,
  },
  title: {
    margin: "0 0 1rem 0",
    color: theme.colors.text,
    fontSize: "2rem",
    fontWeight: theme.typography.h2.fontWeight,
    letterSpacing: "-0.02em",
    lineHeight: "1.2",
  },
  meta: {
    display: "flex",
    gap: "1rem",
    marginBottom: "1.5rem",
    flexWrap: "wrap",
    alignItems: "center",
  },
  statusBadge: {
    padding: "0.5rem 1rem",
    borderRadius: theme.borderRadius.full,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "600",
  },
  statusDraft: {
    backgroundColor: "#fef3c7",
    color: "#92400e",
  },
  statusActive: {
    backgroundColor: theme.colors.successLight,
    color: "#065f46",
  },
  statusCompleted: {
    backgroundColor: theme.colors.backgroundLight,
    color: theme.colors.textMuted,
  },
  cost: {
    fontWeight: "600",
    color: theme.colors.text,
    fontSize: theme.typography.body.fontSize,
  },
  description: {
    lineHeight: "1.6",
    color: theme.colors.textLight,
    marginBottom: "1rem",
    fontSize: theme.typography.body.fontSize,
  },
  address: {
    color: theme.colors.textLight,
    fontSize: theme.typography.body.fontSize,
  },
  contractorSection: {
    background: theme.colors.white,
    padding: "2rem",
    borderRadius: theme.borderRadius.lg,
    boxShadow: theme.shadows.md,
    marginBottom: "2rem",
    border: `1px solid ${theme.colors.borderLight}`,
  },
  sectionTitle: {
    margin: "0 0 1.5rem 0",
    color: theme.colors.text,
    fontSize: theme.typography.h3.fontSize,
    fontWeight: theme.typography.h3.fontWeight,
    letterSpacing: "-0.02em",
  },
  contractorInfo: {
    color: theme.colors.textLight,
    fontSize: theme.typography.body.fontSize,
    marginBottom: "0.5rem",
  },
  noContractor: {
    textAlign: "center",
    padding: "2rem 1rem",
  },
  noContractorText: {
    color: theme.colors.textMuted,
    marginBottom: "1rem",
    fontSize: theme.typography.body.fontSize,
  },
  assignButton: {
    padding: "0.875rem 2rem",
    backgroundColor: theme.colors.primary,
    color: theme.colors.white,
    border: "none",
    borderRadius: theme.borderRadius.md,
    cursor: "pointer",
    fontSize: theme.typography.body.fontSize,
    fontWeight: "600",
    transition: "all 0.2s ease",
    boxShadow: theme.shadows.sm,
  },
}
