export const projectDetailStyles = {
  container: "max-w-[1200px] mx-auto py-8 px-4 min-h-[calc(100vh-100px)]",
  loading: "text-center py-12 px-4 text-lg text-text-light",
  error: "text-center py-12 px-4 text-lg",
  errorButton: "mt-8 py-3.5 px-6 bg-black text-white border-0 rounded-md cursor-pointer text-base font-semibold transition-all duration-200 hover:bg-gray-800",
  header: "flex justify-between items-center mb-8 gap-4 flex-wrap",
  backButton: "py-3.5 px-6 border border-border rounded-md cursor-pointer text-base bg-white text-text font-semibold transition-all duration-200 hover:bg-gray-50",
  editButton: "py-3.5 px-6 bg-text text-white border-0 rounded-md cursor-pointer text-[0.9375rem] font-semibold transition-all duration-200 shadow-sm tracking-[0.01em] hover:bg-gray-700",
  infoCard: "bg-white p-8 rounded-lg shadow-md mb-8 border border-gray-100",
  title: "m-0 mb-4 text-text text-[2rem] font-bold tracking-tight leading-tight",
  meta: "flex gap-4 mb-6 flex-wrap items-center",
  statusBadge: "py-2 px-4 rounded-full text-sm font-semibold",
  statusDraft: "bg-amber-100 text-amber-800",
  statusActive: "bg-emerald-50 text-emerald-800",
  statusCompleted: "bg-background text-gray-500",
  cost: "font-semibold text-text text-base",
  description: "leading-relaxed text-text-light mb-4 text-base",
  address: "text-text-light text-base",
  contractorSection: "bg-white p-8 rounded-lg shadow-md mb-8 border border-gray-100",
  sectionTitle: "m-0 mb-6 text-text text-xl font-bold tracking-tight",
  contractorInfo: "text-text-light text-base mb-2",
  noContractor: "text-center py-8 px-4",
  noContractorText: "text-gray-400 mb-4 text-base",
  assignButton: "py-3.5 px-8 bg-primary text-white border-0 rounded-md cursor-pointer text-base font-semibold transition-all duration-200 shadow-sm hover:bg-blue-600",
}
